//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::event::Entity as Event;
pub use super::participant::Entity as Participant;
pub use super::submission::Entity as Submission;
pub use super::team::Entity as Team;
